#!/bin/sh
# Host-side provisioning for the dev `garage` docker-compose service.
#
# The dxflrs/garage:v2.3.0 image is distroless (only the /garage binary, no shell),
# so this script runs ON THE HOST and shells out to `docker compose exec` — each
# command runs /garage directly inside the running container. Run this AFTER
# `docker compose -f docker/docker-compose.yml up -d garage`. It is idempotent:
# safe to re-run against a persisted `garagedata` volume.
set -e
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
COMPOSE="$SCRIPT_DIR/../docker-compose.yml"
CONF=/etc/garage/garage.toml
BUCKET=blog-media
KEYNAME=blog-app
CREDS="$SCRIPT_DIR/credentials.env"

# `docker compose exec` against the running garage service; -T disables the pty so
# command output is clean for parsing.
gc() { docker compose -f "$COMPOSE" exec -T garage /garage -c "$CONF" "$@"; }

# Wait for the control RPC to answer.
until gc status >/dev/null 2>&1; do
  echo "waiting for garage..."
  sleep 1
done

# Garage v2.x starts a fresh node with NO cluster layout; bucket/key ops return
# "Layout not ready" until the node is assigned a role and the layout is applied.
# On a persisted volume the layout already exists, so guard with a check.
if gc status | grep -q "NO ROLE ASSIGNED"; then
  NODE=$(gc status | awk '/^[0-9a-f]{16}/{print $1; exit}')
  gc layout assign -z dc1 -c 1G "$NODE"
  gc layout apply --version 1
fi
# Wait until the layout is usable (bucket list stops returning "Layout not ready").
until gc bucket list >/dev/null 2>&1; do
  sleep 1
done

# Create the bucket if it does not exist (ignore "already exists" on re-runs).
gc bucket create "$BUCKET" 2>/dev/null || true

# Create or reuse the access key. The secret is shown ONLY on first creation
# (`key info` redacts it afterwards), so capture it then and write it to
# credentials.env for the developer to copy into .env.
if ! gc key info "$KEYNAME" >/dev/null 2>&1; then
  OUT=$(gc key create "$KEYNAME")
  KEY_ID=$(echo "$OUT" | awk '/^Key ID:/{print $3}')
  SECRET=$(echo "$OUT" | awk '/^Secret key:/{print $3}')
  cat > "$CREDS" <<EOF
# Generated by docker/garage/garage-init.sh — copy these into your .env
S3_ACCESS_KEY_ID=$KEY_ID
S3_SECRET_ACCESS_KEY=$SECRET
S3_ENDPOINT=http://localhost:3900
S3_REGION=garage
S3_BUCKET=$BUCKET
S3_PUBLIC_BASE=http://localhost:3900/$BUCKET
S3_FORCE_PATH_STYLE=true
EOF
  echo "garage init complete — credentials written to $CREDS"
else
  KEY_ID=$(gc key info "$KEYNAME" | awk '/^Key ID:/{print $3}')
  echo "garage init complete — key '$KEYNAME' already exists (id=$KEY_ID);"
  echo "  secret kept from first run in $CREDS (not re-readable)."
fi

# Grant the key read+write on the bucket (idempotent).
gc bucket allow --read --write "$BUCKET" --key "$KEY_ID"

# NOTE: anonymous public read is not configured. Garage v2.x has no `bucket allow
# --public` flag; browser fetches of S3 object URLs would 403. The integration tests
# use signed getObject via the storage helper, and local development can use the
# local-disk storage driver for browser preview. Configure public read separately
# if anonymous browser fetch is needed.