#!/bin/sh
set -e
CONF=/etc/garage/garage.toml
BUCKET=blog-media
CREDS=/etc/garage/credentials.env

# Wait for Garage RPC to be ready.
until garage -c "$CONF" status >/dev/null 2>&1; do
  echo "waiting for garage..."
  sleep 1
done

# Create the bucket if it does not exist.
if ! garage -c "$CONF" bucket list | grep -q "$BUCKET"; then
  garage -c "$CONF" bucket create "$BUCKET"
fi

# Public-read so uploaded images are fetchable by the browser without signed URLs.
garage -c "$CONF" bucket allow --read --public "$BUCKET" 2>/dev/null || \
  garage -c "$CONF" bucket allow --public-read "$BUCKET" 2>/dev/null || true

# Create (or reuse) an access key for the app. `garage key new` generates a random
# secret; we capture it once and write it to credentials.env. On re-runs the key
# already exists, so we just re-list it.
KEY_ID=$(garage -c "$CONF" key list --show-secrets 2>/dev/null | awk '/blog-app/{print $1; exit}')
if [ -z "$KEY_ID" ]; then
  OUT=$(garage -c "$CONF" key new --name blog-app)
  KEY_ID=$(echo "$OUT" | awk '/Key ID:/{print $3}')
  SECRET=$(echo "$OUT" | awk '/Secret key:/{print $3}')
else
  SECRET=$(garage -c "$CONF" key list --show-secrets 2>/dev/null | awk -v k="$KEY_ID" '$0 ~ k {print $2; exit}')
fi
garage -c "$CONF" bucket allow --read --write "$BUCKET" --key "$KEY_ID"

cat > "$CREDS" <<EOF
# Generated by docker/garage/garage-init.sh — copy these into your .env
S3_ACCESS_KEY_ID=$KEY_ID
S3_SECRET_ACCESS_KEY=$SECRET
S3_ENDPOINT=http://localhost:3900
S3_REGION=garage
S3_BUCKET=$BUCKET
S3_PUBLIC_BASE=http://localhost:3900/$BUCKET
S3_FORCE_PATH_STYLE=true
EOF
echo "garage init complete — credentials in $CREDS"